before_script:
  - "bin/rake neo4j:install[$NEO4J_VERSION] --trace"
  - "bin/rake neo4j:config[development,7474] --trace"
  - "if [ -f ./db/neo4j/development/conf/neo4j-wrapper.conf ]; then WRAPPER=-wrapper; fi"
  - "echo 'dbms.memory.pagecache.size=600m' >> ./db/neo4j/development/conf/neo4j.conf"
  - "echo 'dbms.memory.heap.max_size=600' >> ./db/neo4j/development/conf/neo4j$WRAPPER.conf"
  - "echo 'dbms.memory.heap.initial_size=600' >> ./db/neo4j/development/conf/neo4j$WRAPPER.conf"
  - "bin/rake neo4j:start --trace"
  - "sleep 20"
script:
  - "bundle exec rspec $RSPEC_OPTS"
language: ruby
cache: bundler
sudo: false
jdk: oraclejdk8
rvm:
  - 2.3.1
  - 2.2.5
  - jruby-9.1.12.0
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_URL="http://localhost:7474"
    - NEO4J_BOLT_URL="bolt://localhost:7472"
  matrix:
    - NEO4J_VERSION=community-3.2.1
matrix:
  include:
    - script: "bundle exec rubocop"
      rvm: 2.3.1
      jdk:
      before_script:
      env: "RUBOCOP=true"

    # Older versions of Neo4j with latest version of Ruby
    - rvm: 2.3.1
      env: NEO4J_VERSION=community-3.1.5
    - rvm: 2.3.1
      env: NEO4J_VERSION=community-2.3.11
    - rvm: 2.3.1
      env: NEO4J_VERSION=community-2.1.8

    # Older versions of Neo4j with latest version of jRuby
    - rvm: jruby-9.1.12.0
      env: NEO4J_VERSION=community-3.1.5
    - rvm: jruby-9.1.12.0
      env: NEO4J_VERSION=community-2.3.11
    - rvm: jruby-9.1.12.0
      env: NEO4J_VERSION=community-2.1.8

    # NEW_NEO4J_SESSIONS
    - rvm: jruby-9.1.12.0
      env: RSPEC_OPTS="--tag new_cypher_session" NEO4J_VERSION=community-2.3.11 NEW_NEO4J_SESSIONS=true

    # Enterprise
    - rvm: 2.3.1
      env: NEO4J_VERSION=enterprise-3.2.1

after_failure:
  - cat ./db/neo4j/development/logs/neo4j.log
  - cat ./db/neo4j/development/logs/debug.log
  - cat ./db/neo4j/development/conf/neo4j.conf
